# Generated by Django 4.1.5 on 2023-01-28 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image_s3_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_s3_path',
            field=models.ImageField(blank=True, null=True, upload_to='user_images', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
