# Generated by Django 4.1.4 on 2022-12-16 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('208fd4f3-0ab3-42ca-a4cd-3890988dce3f'), primary_key=True, serialize=False, unique=True),
        ),
    ]
