# Generated by Django 4.1.5 on 2023-01-28 16:18

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_page_image_alter_page_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c8c0ab9a-9054-4858-b2b3-75814f2d4e8d'), primary_key=True, serialize=False),
        ),
    ]
