# Generated by Django 4.1.5 on 2023-02-02 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_page_image_alter_page_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d7cb2bf7-fd80-49a6-8607-5e0f75a8169d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
